Prédio Comercial/Models/Proprietarios.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Prédio_Comercial.Models
{
    public class Proprietarios
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public int Sala { get; set; }
        public string? Documento { get; set; }
        public int VisitantesId { get; set; }
        public List<Visitantes>? Visitantes { get; set; }
        [NotMapped]
        public List<int>? VisitantesSelecionados { get; set; } = new List<int>();

    }
}

Prédio Comercial/Controllers/ProprietariosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Prédio_Comercial.Interface;
using Prédio_Comercial.Models;
using Prédio_Comercial.Service;
using System.Linq;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace Prédio_Comercial.Controllers
{
    public class ProprietariosController : Controller
    {
        private readonly IProprietarios _proprietarios;
        private readonly ApplicationDbContext _contex;
        private readonly ISessionUsuary _sessionUsuary;
        public ProprietariosController(IProprietarios proprietarios, ApplicationDbContext contex, ISessionUsuary sessionUsuary)
        {
            _proprietarios = proprietarios;
            _contex = contex;
            _sessionUsuary = sessionUsuary;
        }
        public async Task<IActionResult> Index()
        {
            //await _contex.Visitantes.ToListAsync();   
            return View(await _proprietarios.BuscarTodosProprietarios());
        }
        public IActionResult Detalhes()
        {
            return View();
        }
        public async Task<IActionResult> BuscarPorId(int id)
        {
            if(ModelState.IsValid)
            {
                return View(await _proprietarios.BuscarPorId(id));
            }
            return RedirectToAction("Index");
        }
        [HttpGet("Proprietarios/AdicionarProprietario")]
        public async Task<IActionResult> AdicionarView()
        {
            var visitantes = await _contex.Visitantes.ToListAsync();
            ViewBag.Visitantes = new SelectList(visitantes, "Id", "Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Adicionar(Proprietarios proprietarios)
        {
            if(ModelState.IsValid)
            {
                var user = _sessionUsuary.BuscarSessao();
                if (user.Admin == true)
                {
                    proprietarios.Visitantes = await _contex.Visitantes.Where(a => proprietarios.VisitantesSelecionados!.Contains(a.Id)).ToListAsync();
                    await _proprietarios.AdicionarProprietario(proprietarios);
                    var visitantes = await _contex.Visitantes.ToListAsync();
                    ViewBag.Visitantes = new SelectList(visitantes, "Id", "Name");
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Alterar(int id)
        {
            var _Proprietario = await _contex.Proprietarios.Include(a => a.Visitantes).FirstOrDefaultAsync(a => a.Id == id);
            var visitantes = await _contex.Visitantes.ToListAsync();
            var visitantesselecionados = await _contex.Visitantes.Where(a=>_Proprietario!.VisitantesSelecionados!
            .Contains(id))
            .ToListAsync();
            _Proprietario!.VisitantesSelecionados = _Proprietario?.Visitantes!.Select(a=>a.Id).ToList();
            ViewBag.Visitantes = new SelectList(visitantes, "Id", "Name", visitantesselecionados);
            return View(_Proprietario);
        }
        
            public async Task<IActionResult> Update(int id, Proprietarios Proprietario)
            {
                var propri = await _contex.Proprietarios.Include(a=>a.Visitantes).FirstOrDefaultAsync(a=>a.Id == id);
                propri!.Visitantes = await _contex.Visitantes.Where(a => Proprietario.VisitantesSelecionados!.Contains(a.Id)).ToListAsync();
                
                propri.Sala = Proprietario.Sala;
                propri.Name = Proprietario.Name;
                propri.Documento = Proprietario.Documento;
                propri.VisitantesSelecionados = Proprietario.VisitantesSelecionados;

            
                _contex.Proprietarios.Update(propri);
                await _contex.SaveChangesAsync();
                
                return RedirectToAction("Index");
            }
        public async Task<IActionResult> Deletar(int id)
        {
            var _Proprietario = await _contex.Proprietarios.Include(a=>a.Visitantes).FirstOrDefaultAsync(a=>a.Id==id);
            if (_Proprietario == null)
            {
                return RedirectToAction("Index");
            }
            _contex.Proprietarios.Remove(_Proprietario);
            await _contex.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Prédio Comercial/Views/Proprietarios/AdicionarView.cshtml
@model Prédio_Comercial.Models.Proprietarios;
<style>
    .content{
        padding: 10px;
        margin-left: 0px;
        margin-bottom: 10px;
    }
</style>
<div class="content container-fluid">
    <div class="row">
        <div class="col-md-12">
            <form asp-controller="Proprietarios" asp-action="Adicionar">
                <div class="col-md-6">
                    <label class="form-label" asp-for="Name">Nome</label>
                    <input class="form-control" asp-for="Name" />
                    <span asp-validation-for="Name"></span>
                </div>
                <div class="col-md-6">
                    <label class="form-label" asp-for="Sala">Sala Comercial</label>
                    <input class="form-control" type="number" asp-for="Sala" />
                    <span asp-validation-for="Sala"></span>
                </div>
                <div class="col-md-4">
                    <label class="form-label" asp-for="Documento">RG / CPF</label>
                    <input class="form-control" asp-for="Documento" />
                    <span asp-validation-for="Documento"></span>
                </div>
                <div class="col-md-8">
                    <label asp-for="Visitantes">Adicionar Visitantes</label>
                    <select asp-for="VisitantesSelecionados" asp-items="ViewBag.Visitantes" class="form-control" multiple>
                    </select>
                </div>
                <div class="col-md-2">
                    <button type="submit" class="btn btn-light">Cadastrar</button>
                </div>
            </form>
        </div>
    </div>
</div>

Prédio Comercial/Views/Proprietarios/Alterar.cshtml
@model Prédio_Comercial.Models.Proprietarios;

<style>
    .content {
        padding: 10px;
        margin-left: 0px;
        margin-bottom: 10px;
    }
</style>
<div class="content container-fluid">
    <div class="row">
        <div class="col-md-12">
            <form asp-controller="Proprietarios" asp-action="Update" method="post">
                <input type="hidden" asp-for="Id" />
                <div class="col-md-6">
                    <label class="form-label" asp-for="Name">Nome</label>
                    <input class="form-control" asp-for="Name" />
                    <span asp-validation-for="Name"></span>
                </div>
                <div class="col-md-6">
                    <label class="form-label" asp-for="Sala">Sala Comercial</label>
                    <input class="form-control" type="number" asp-for="Sala" />
                    <span asp-validation-for="Sala"></span>
                </div>
                <div class="col-md-4">
                    <label class="form-label" asp-for="Documento">RG / CPF</label>
                    <input class="form-control" asp-for="Documento" />
                    <span asp-validation-for="Documento"></span>
                </div>
                <div class="col-md-8">
                    <label asp-for="VisitantesSelecionados" class="form-label">Adicionar Visitantes</label>
                    <select asp-for="VisitantesSelecionados" asp-items="ViewBag.Visitantes" class="form-select" multiple>
                    </select>
                </div>
                <div class="col-md-2">
                    <button type="submit" class="btn btn-light">Atualizar</button>
                </div>
            </form>
        </div>
    </div>
</div>

Prédio Comercial/Views/Proprietarios/Index.cshtml
@model IEnumerable<Prédio_Comercial.Models.Proprietarios>;


<style>
    .content {
        margin-left: 0px;
        padding: 20px;
    }
</style>

<div class="content container-fluid">
    <div class="row">
        <div class="col-md-8">
            <div class="table-responsive-sm">
                <h2 class="card-subtitle">Proprietarios</h2>
                <a asp-controller="Proprietarios" asp-action="AdicionarView" class="btn btn-info">Adicionar Novo Proprietário</a>
                <table class="table table-dark">
                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model=>model.Name)</th>
                            <th>@Html.DisplayNameFor(model=>model.Documento)</th>
                            <th>@Html.DisplayNameFor(model=>model.Sala)</th>
                            <th>@Html.DisplayNameFor(model=>model.Visitantes)</th>
                            <th>@Html.DisplayNameFor(model=>model.VisitantesId)</th>
                            <th></th>
                            <th></th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var x in Model)
                        {
                            <tr>
                                <td id="Nome">@Html.DisplayFor(modelitem=> x.Name)</td>


                                <td>@Html.DisplayFor(modelitem=> x.Documento)</td>

                                <td>@Html.DisplayFor(modelitem=>x.Sala)</td>
                                <td>@if (x.Visitantes != null && x.Visitantes.Any())
                                    {
                                        @foreach (var visitantes in x.Visitantes)
                                        {
                                            @visitantes.Name<br />
                                            @visitantes.Dataentrada<br />
                                        }
                                    }

                                    else
                                    {
                                        Console.WriteLine("Nâo há visitantes");
                                    }
                                </td>
                                <td>
                                    @Html.DisplayFor(modelitem=>x.VisitantesId)
                                </td>
                                <td>
                                    <a asp-controller="Proprietarios" asp-action="Alterar" asp-route-id="@x.Id" class="btn btn-primary btn-editar">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-building" viewBox="0 0 16 16">
                                            <path d="M4 2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm3 0a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm3.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5zM4 5.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zM7.5 5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5zm2.5.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zM4.5 8a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5zm2.5.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm3.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5z" />
                                            <path d="M2 1a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1zm11 0H3v14h3v-2.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 .5.5V15h3z" />
                                        </svg>
                                    </a>
                                    </td>
                                    <td>
                                    <a asp-controller="Proprietarios" asp-action="Deletar" asp-route-id="@x.Id" class="btn btn-danger btn-deletar">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-circle-fill" viewBox="0 0 16 16">
                                            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293z" />
                                        </svg>
                                    </a>

                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <a asp-controller="Proprietarios" asp-action="Index" class="btn btn-light">Voltar</a>

            </div>
        </div>

    </div>

</div>


@* <div class="col-md-3">
</div>
<!--Aqui é o MODAL que vai abrir o formulário para Edição-->

<div class="modal fade" id="modalEdicao" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Deseja Editar Visitante?</h1>
            <div class="modal-body" id="conteudoModalEdicao">
            </div>
        </div>
    </div>
</div>
<!-- Aqui é onde abre o modal para confirmação de Deletar-->

<div class="modal fade" id="modalDelete" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Deseja Deletar Visitante?</h1>
            <div class="modal-body" id="conteudoModalDelete">
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

<script>
    $(document).ready(function () {
        $('.btn-editar').click(function () {
            const id = $(this).data('id');

            $.ajax({
                type: "GET",
                url: "/Visitantes/Editar/" + id,
                success: function (html) {
                    $('#conteudoModalEdicao').html(html);
                    $('#modalEdicao').modal('show');
                },
                error: function () {
                    alert("Erro ao carregar formulário.");
                }
            });
        });

        $(document).on('submit', '#formEditarVisitante', function (e) {
            e.preventDefault();
            $.ajax({
                type: "POST",
                url: "/Visitantes/Editar/",
                data: $("#formEditarVisitante").serialize(),
                success: function (response) {
                    $('#modalEdicao').modal('hide');
                    location.reload();
                },
                error: function (xhr) {
                    alert("Erro ao salvar dados:" + xhr.responseText);
                }
            });
        });

        // Aqui vai o outro script para abrir o formulário para confirmar o Delete //


        $('.btn-deletar').click(function () {
            const id = $(this).data('id');

            $.ajax({
                type: "GET",
                url: "/Visitantes/Deletar/" + id,
                success: function (html) {
                    $('#conteudoModalDelete').html(html);
                    $('#modalDelete').modal('show');
                },
                error: function () {
                    alert("Erro ao carregar Visitante");
                }
            });
        });

        $(document).on('submit', '#formDeletarVisitante', function (e) {
            e.preventDefault();
            $.ajax({
                type: "POST",
                url: "/Visitantes/DeletarVisitante/",
                data: $("#formDeletarVisitante").serialize(),
                success: function (response) {
                    $('#modalDelete').modal('hide');
                    location.reload();
                },
                error: function (xhr) {
                    alert("Erro ao deletar o Visitante :" + xhr.responseText);
                }
            });
        });
    });
</script>
 *@