Prédio Comercial/Controllers/AcessosController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Prédio_Comercial.ActionFilter;
using Prédio_Comercial.Interface;
using Prédio_Comercial.Models;
using Prédio_Comercial.Models.DTO;
using Prédio_Comercial.Service;

namespace Prédio_Comercial.Controllers
{
    public class AcessosController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IFiltragemDePagina _filtragemDePagina;
        private readonly IMapper _Mapper;
        public AcessosController(ApplicationDbContext applicationDbContext, IFiltragemDePagina filtragemDePagina, IMapper mapper)
        {
            _context = applicationDbContext;
            _filtragemDePagina = filtragemDePagina;
            _Mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var Acesso = await _context.Acessos.Include(x=>x.Usuarios).Include(x=>x.Visitante).ToListAsync();
            var _AcessoMapeado = _Mapper.Map<List<AcessosGetDTO>>(Acesso);
            return View(_AcessoMapeado);
        }
  
        public async Task<IActionResult> Details(int id)
        {
            var Visitante = new SelectList(await _context.Visitantes.ToListAsync(), "Id", "Name");
            var Usuarios = new SelectList(await _context.Usuarios.ToListAsync(), "Id", "Login");
            ViewBag.Visitante = Visitante;
            ViewBag.Usuarios = Usuarios;    
            var acessoId = await _context.Acessos.FindAsync(id);
            return PartialView(acessoId);
        }
        public async Task<IActionResult> Criar()
        {
            //var acesso = _filtragemDePagina.Buscar();
            //if(acesso == null)
            //{
            //    return RedirectToAction("Index");
            //}
            ViewBag.Visitantes = new SelectList(await _context.Visitantes.ToListAsync(), "Id", "Name");
            ViewBag.Usuarios = new SelectList(await _context.Usuarios.ToListAsync(), "Id", "Login");

            return View();
        }

        public async Task<IActionResult> CriarAcesso(Acessos acessos)
        {
            if (ModelState.IsValid)
            {
                var _NewAcesso = await _context.Acessos.AddAsync(acessos);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.Visitantes = new SelectList(await _context.Visitantes.ToListAsync(), "Id", "Name");
            ViewBag.Usuarios = new SelectList(await _context.Usuarios.ToListAsync(), "Id", "Login");
            return View("Criar", acessos);
        }

        public async Task<IActionResult> Editar(int id)
        {
            var acesso = await _context.Acessos.FindAsync(id);
            return View(acesso);
        }

        public async Task<IActionResult> Editar(int id, Acessos acessos)
        {
            var acesso = await _context.Acessos.FindAsync(id);
            acessos.id = acesso.id;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

    }
}

Prédio Comercial/Controllers/DashboardController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Prédio_Comercial.ActionFilter;
using Prédio_Comercial.Models;
using Prédio_Comercial.Service;

namespace Prédio_Comercial.Controllers
{
    [PaginaParaUsuarioAdmin]
    public class DashboardController : Controller
    {
        private readonly ApplicationDbContext _Context;
        private readonly IMapper _Mapper;
        public DashboardController(ApplicationDbContext context, IMapper mapper)
        {
            _Context = context;
            _Mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            var acessos = await _Context.Acessos.Include(a => a.Visitante).Include(b=>b.Usuarios).ToListAsync();
            acessos.Select(a => a.Usuarios.Login).ToList();
            acessos.Select(b=>b.Visitante.Name).ToList();
            ViewData["ItemCount"] = acessos.Count();
            return View(acessos);
        }
        public async Task<IActionResult> Logger(DateTime date)
        {
            var filter = await _Context.LogsMensage.Where(a=>a.CreatedAt == date.Date).ToListAsync();
            //var Logger = await _Context.LogsMensage.Include(a=>a.Usuarios).Where(a=>a.Usuarios!= null).ToListAsync();
            await _Context.LogsMensage.Select(a => a.Usuarios).ToListAsync();
            var mapperLoger = _Mapper.Map<List<LogAuditoria>>(filter);
            ViewData["Data"] = date.Date.ToString("dd/MM/YYYY");
            return View(mapperLoger);
        }
    }
}

Prédio Comercial/Controllers/OcorrenciasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Prédio_Comercial.Models;
using Prédio_Comercial.Service;

namespace Prédio_Comercial.Controllers
{
    public class OcorrenciasController : Controller
    {
        private readonly ApplicationDbContext _context;
        public OcorrenciasController(ApplicationDbContext applicationDbContext)
        {
            _context = applicationDbContext;
        }
        public async Task<IActionResult> Index()
        {
            var ListaDeOcorrencias = await _context.Ocorrencias.ToListAsync();
            return View(ListaDeOcorrencias);
        }
        public ActionResult cadastrar()
        {
            var ocorrencias = _context.Ocorrencias.ToList();
            ViewBag.ocorrencias = new SelectList(ocorrencias);
            return PartialView("cadastrar");
        }
        public async Task<IActionResult> CadastrarOcorrencia(Ocorrencias ocorrencias)
        {
            if(ModelState.IsValid)
            {
                await _context.Ocorrencias.AddAsync(ocorrencias);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return BadRequest();
        }
        public async Task<IActionResult> ExcluirOcorrencia(int id)
        {
            var ocorrencia = await _context.Ocorrencias.FirstOrDefaultAsync(a=>a.Id == id);
            if(ocorrencia != null && ocorrencia.Ativa != true)
            {
                _context.Ocorrencias.Remove(ocorrencia);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

Prédio Comercial/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using Prédio_Comercial.ActionFilter;
using Prédio_Comercial.Interface;
using Prédio_Comercial.Models;
using Prédio_Comercial.Models.DTO;
using Prédio_Comercial.Repository;
using Prédio_Comercial.Service;

namespace Prédio_Comercial.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly IUsuarios _usuarios;
        private readonly ISessionUsuary _sessionUsuary;
        private readonly IFiltragemDePagina _filtragemDePagina;
        public UsuariosController(IUsuarios usuarios, ISessionUsuary sessionUsuary, IFiltragemDePagina filtragemDePagina)
        {
            _usuarios = usuarios;
            _sessionUsuary = sessionUsuary;
            _filtragemDePagina = filtragemDePagina;
        }
        public async Task<IActionResult> Login()
        {
            return View();
        }
        public async Task<IActionResult> LayoutNovoTeste()
        {
            var usuarios = _usuarios.BuscarTodos();
            ViewBag.Usuario = usuarios;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(Usuarios usuarios)
        {
            var login = await _usuarios.Login(usuarios);
            if(login == null)
            {
                TempData["MensageErro"] = $"Login ou Senha incorreto";
                return View(usuarios);
            }
            _sessionUsuary.RemoverSessao();
             _sessionUsuary.CriarSessao(login);
            return RedirectToAction("Index", "Visitantes");

        }
        public async Task<IActionResult> Index()
        {
                
                return View();
        }
        public async Task<IActionResult> BuscarUsuario(int id)
        {
            if (id == 0) { BadRequest();  }
            var usuario = await _usuarios.BuscarPorId(id);
            return View(usuario);
        }
        public async Task<IActionResult> Detalhes(int id)
        {
           var usuarios = await _usuarios.BuscarPorId(id);
            if(usuarios == null) return NotFound();
            return View(usuarios);
        }
        public async Task<IActionResult> Criar()
        {
            var _VerifyIsAdmin = _filtragemDePagina.Buscar();
            if(_VerifyIsAdmin.Admin == false)
            {
                return RedirectToAction("Index");
            }
            ViewBag.NameUser = _VerifyIsAdmin.Login;
            //var usuarioLogado = _sessionUsuary.BuscarSessao();
            return View();
        }
        public async Task<IActionResult> CriarUsuario(UsuariosDTO usuarios)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //usuarios.Password = _usuarios.GerarHash(usuarios.Password);

                    await _usuarios.Criar(usuarios);
                    TempData["MenssageSucesso"] = $"Usuário Criado com Sucesso {usuarios.Login}";
                    return RedirectToAction("Criar");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(String.Empty, "Nâo foi possível criar usuário");
            }
            TempData["MenssageError"] = $"Não foi possível criar o usuário {usuarios.Login} verifique os dados";
            return RedirectToAction("Criar");
        }

        public async Task<IActionResult> EditarUsuario(int id)
        {
            Usuarios usuarios = await _usuarios.BuscarPorId(id);
            return View(usuarios);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditarUsuario(int id, Usuarios usuarios)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _usuarios.Editar(id, usuarios);
                    return RedirectToAction("Index");
                }
                
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(String.Empty, "Não foi possível editar o Usuário");
            }
            return View(usuarios);
        }

        public async Task<IActionResult> Deletar()
        {
            return View();
        }
        public async Task<IActionResult> Deletar(int id, Usuarios usuarios)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _usuarios.Deletar(id, usuarios);
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(String.Empty, "Não foi possível deletar o Usuário");
            }
            return RedirectToAction("Index");
        }
    }

}

Prédio Comercial/Views/Shared/Components/MenuComponent/Default.cshtml
@model Usuarios;

<meta name="viewport" content="width=device-width, initial-scale=1.0" />


<style>
    a {
        color: white;
        display: block;
        transition: 0.3s;
        text-align: initial;
        padding: 20px;
    }

        a:hover {
            background: #333;
            color: orange;
        }
</style>
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="sidebar d-flex flex-column">
                <a>Bem vindo @Model.Login</a>
                <a asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                <a asp-controller="DashBoardDTO" asp-action="Index">Dashboard</a>

                <a class="" asp-area="" asp-controller="Acessos" asp-action="Index">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-building-fill-up" viewBox="0 0 16 16">
                        <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7m.354-5.854 1.5 1.5a.5.5 0 0 1-.708.708L13 11.707V14.5a.5.5 0 0 1-1 0v-2.793l-.646.647a.5.5 0 0 1-.708-.708l1.5-1.5a.5.5 0 0 1 .708 0" />
                        <path d="M2 1a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v7.256A4.5 4.5 0 0 0 12.5 8a4.5 4.5 0 0 0-3.59 1.787A.5.5 0 0 0 9 9.5v-1a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .39-.187A4.5 4.5 0 0 0 8.027 12H6.5a.5.5 0 0 0-.5.5V16H3a1 1 0 0 1-1-1zm2 1.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5m3 0v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5m3.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5zM4 5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5M7.5 5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5zm2.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5M4.5 8a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5z" />
                    </svg>Acessos
                </a>

                <a class="" asp-area="" asp-controller="Visitantes" asp-action="Index">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-passport" viewBox="0 0 16 16">
                        <path d="M8 5a3 3 0 1 0 0 6 3 3 0 0 0 0-6M6 8a2 2 0 1 1 4 0 2 2 0 0 1-4 0m-.5 4a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1z" />
                        <path d="M3.232 1.776A1.5 1.5 0 0 0 2 3.252v10.95c0 .445.191.838.49 1.11.367.422.908.688 1.51.688h8a2 2 0 0 0 2-2V4a2 2 0 0 0-1-1.732v-.47A1.5 1.5 0 0 0 11.232.321l-8 1.454ZM4 3h8a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1" />
                    </svg>Visitantes
                </a>

                <a class="" asp-area="" asp-controller="Usuarios" asp-action="Criar">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-person-fill" viewBox="0 0 16 16">
                        <path d="M12 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2m-1 7a3 3 0 1 1-6 0 3 3 0 0 1 6 0m-3 4c2.623 0 4.146.826 5 1.755V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-1.245C3.854 11.825 5.377 11 8 11" />
                    </svg>Usuários
                </a>

                <a class="" asp-area="" asp-controller="Proprietarios" asp-action="Index">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-badge" viewBox="0 0 16 16">
                        <path d="M6.5 2a.5.5 0 0 0-.5.5V3H4a2 2 0 0 0-2 2v5.5a.5.5 0 0 0 1 0V5a1 1 0 0 1 1-1h2v.5a.5.5 0 0 0 1 0V4h2v.5a.5.5 0 0 0 1 0V4h2a1 1 0 0 1 1 1v5.5a.5.5 0 0 0 1 0V5a2 2 0 0 0-2-2h-2v-.5a.5.5 0 0 0-.5-.5h-3z" />
                        <path d="M5 12a3 3 0 1 1 6 0H5z" />
                    </svg>Proprietários
                </a>
                <a class="" asp-area="" asp-controller="Ocorrencias" asp-action="Index">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-exclamation-octagon" viewBox="0 0 16 16">
                        <path d="M7.001 1.067a1 1 0 0 1 1.998 0l.25 2a1 1 0 0 1-.998 1.118h-1.5a1 1 0 0 1-.998-1.118l.25-2zM7.5 6a.5.5 0 0 1 1 0v4a.5.5 0 0 1-1 0V6zm0 6.5a.5.5 0 0 1 1 0 .5.5 0 0 1-1 0z" />
                        <path d="M11.46.146a.5.5 0 0 1 .354.146l3.5 3.5a.5.5 0 0 1 .146.354v7.708a.5.5 0 0 1-.146.354l-3.5 3.5a.5.5 0 0 1-.354.146H4.54a.5.5 0 0 1-.354-.146l-3.5-3.5a.5.5 0 0 1-.146-.354V4.146a.5.5 0 0 1 .146-.354l3.5-3.5a.5.5 0 0 1 .354-.146h6.92zM4.707 1H11.293L15 4.707v6.586L11.293 15H4.707L1 11.293V4.707L4.707 1z" />
                    </svg>Ocorrências
                </a>
            </div>
        </div>
    </div>
</div>



<nav class="navbar bg-dark border-bottom border-body navlarge" data-bs-theme="dark">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <a>Bem vindo @Model.Login</a>
            </div>
        </div>
    </div>
    <a class="" asp-area="" asp-controller="Acessos" asp-action="Index">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-building-fill-up" viewBox="0 0 16 16">
            <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7m.354-5.854 1.5 1.5a.5.5 0 0 1-.708.708L13 11.707V14.5a.5.5 0 0 1-1 0v-2.793l-.646.647a.5.5 0 0 1-.708-.708l1.5-1.5a.5.5 0 0 1 .708 0" />
            <path d="M2 1a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v7.256A4.5 4.5 0 0 0 12.5 8a4.5 4.5 0 0 0-3.59 1.787A.5.5 0 0 0 9 9.5v-1a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .39-.187A4.5 4.5 0 0 0 8.027 12H6.5a.5.5 0 0 0-.5.5V16H3a1 1 0 0 1-1-1zm2 1.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5m3 0v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5m3.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5zM4 5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5M7.5 5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5zm2.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5M4.5 8a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5z" />
        </svg>Acessos
    </a>

    <a class="" asp-area="" asp-controller="Visitantes" asp-action="Index">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-passport" viewBox="0 0 16 16">
            <path d="M8 5a3 3 0 1 0 0 6 3 3 0 0 0 0-6M6 8a2 2 0 1 1 4 0 2 2 0 0 1-4 0m-.5 4a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1z" />
            <path d="M3.232 1.776A1.5 1.5 0 0 0 2 3.252v10.95c0 .445.191.838.49 1.11.367.422.908.688 1.51.688h8a2 2 0 0 0 2-2V4a2 2 0 0 0-1-1.732v-.47A1.5 1.5 0 0 0 11.232.321l-8 1.454ZM4 3h8a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1" />
        </svg>Visitantes
    </a>

    <a class="" asp-area="" asp-controller="Usuarios" asp-action="Criar">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-person-fill" viewBox="0 0 16 16">
            <path d="M12 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2m-1 7a3 3 0 1 1-6 0 3 3 0 0 1 6 0m-3 4c2.623 0 4.146.826 5 1.755V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-1.245C3.854 11.825 5.377 11 8 11" />
        </svg>Usuários
    </a>

    <a class="" asp-area="" asp-controller="Proprietarios" asp-action="Index">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-badge" viewBox="0 0 16 16">
            <path d="M6.5 2a.5.5 0 0 0-.5.5V3H4a2 2 0 0 0-2 2v5.5a.5.5 0 0 0 1 0V5a1 1 0 0 1 1-1h2v.5a.5.5 0 0 0 1 0V4h2v.5a.5.5 0 0 0 1 0V4h2a1 1 0 0 1 1 1v5.5a.5.5 0 0 0 1 0V5a2 2 0 0 0-2-2h-2v-.5a.5.5 0 0 0-.5-.5h-3z" />
            <path d="M5 12a3 3 0 1 1 6 0H5z" />
        </svg>Proprietários
    </a>
    <a class="" asp-area="" asp-controller="Ocorrencias" asp-action="Index">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-exclamation-octagon" viewBox="0 0 16 16">
            <path d="M7.001 1.067a1 1 0 0 1 1.998 0l.25 2a1 1 0 0 1-.998 1.118h-1.5a1 1 0 0 1-.998-1.118l.25-2zM7.5 6a.5.5 0 0 1 1 0v4a.5.5 0 0 1-1 0V6zm0 6.5a.5.5 0 0 1 1 0 .5.5 0 0 1-1 0z" />
            <path d="M11.46.146a.5.5 0 0 1 .354.146l3.5 3.5a.5.5 0 0 1 .146.354v7.708a.5.5 0 0 1-.146.354l-3.5 3.5a.5.5 0 0 1-.354.146H4.54a.5.5 0 0 1-.354-.146l-3.5-3.5a.5.5 0 0 1-.146-.354V4.146a.5.5 0 0 1 .146-.354l3.5-3.5a.5.5 0 0 1 .354-.146h6.92zM4.707 1H11.293L15 4.707v6.586L11.293 15H4.707L1 11.293V4.707L4.707 1z" />
        </svg>Ocorrências
    </a>
</nav>


@* <form class="d-flex mt-3" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" />
                    <button class="btn btn-success" type="submit">Search</button>
                </form> *@

<br />
<br />
<br />