Prédio Comercial/Models/Visitantes.cs
using System.ComponentModel.DataAnnotations;

namespace Prédio_Comercial.Models
{
    public class Visitantes
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string? Name { get; set; }
        [StringLength(14)]
        public string? Documento { get; set; }
        [Required]
        public string? Empresa { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime Dataentrada { get; set; }
        [DataType(DataType.DateTime)]
        public DateTime? DataSaida { get; set; } = DateTime.Now;
        public string? MotivoVisita { get; set; } = "";
        public string? VisitandoQuem { get; set; } = "";
        public Proprietarios? proprietarios { get; set; }
        public int? ProprietariosId { get; set; }

    }
}

Prédio Comercial/Controllers/VisitantesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Prédio_Comercial.ActionFilter;
using Prédio_Comercial.Interface;
using Prédio_Comercial.Models;
using Prédio_Comercial.Repository;
using Prédio_Comercial.Service;

namespace Prédio_Comercial.Controllers
{
    public class VisitantesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IUsuarios _usuarios;
        private readonly ISessionUsuary _sessionUsuary;
        public readonly ILoggerService _loggerService;
        public VisitantesController(ApplicationDbContext applicationDbContext, IUsuarios usuarios, ISessionUsuary sessionUsuary, ILoggerService loggerService)
        {
            _context = applicationDbContext;
            _usuarios = usuarios;
            _sessionUsuary = sessionUsuary;
            _loggerService = loggerService;

        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> ListaVisitantes(string? documento, DateTime dateTime, int id)
        {
            if (!string.IsNullOrEmpty(documento))
            {
                var lista = await _context.Visitantes.Where(x=>x.Documento!.Contains(documento)).ToListAsync();
                return View(lista);
            }
            if (dateTime.Day > 1)
            {
                var listaData = await _context.Visitantes.Where(a=>a.Dataentrada.Day == dateTime.Day).ToListAsync();
                return View(listaData);
            }
            var visitante = await _context.Visitantes.Where(a=>a.Dataentrada<DateTime.Now && a.DataSaida == null).ToListAsync();
            foreach(var a in visitante)
            {
                if(a.Dataentrada < DateTime.Now)
                {
                    ViewBag.Mensagem = $"Ainda não foi dado saída no visitante {a.Name} que entrou na data: {a.Dataentrada}";
                }
            }
            return View(await _context.Visitantes.ToListAsync());
        }
        public IActionResult ListaVisitantesFilter(string documento)
        {
            var Lista = _context.Visitantes!.Where(a=>a.Documento == documento).ToList();
            return View(Lista);
        }
        public async Task<IActionResult> ListaVisitantesAtivo()
        {
            var visitantesAtivos = await _context.Visitantes.Where(x=>x.DataSaida == null).ToListAsync();
            if (visitantesAtivos == null) return BadRequest();
            return View(visitantesAtivos);
        }

        public async Task<IActionResult> NovoVisitante(Visitantes visitantes)
        {
            if(ModelState.IsValid)
            {
                await _loggerService.MessagemLog($"Visitante: {visitantes.Name} Cadastrado com sucesso");
                _sessionUsuary.BuscarSessao();
                _context.Visitantes.Add(visitantes);
                await _context.SaveChangesAsync();
                return RedirectToAction("ListaVisitantes");
            }
            await _loggerService.MessagemLog($"Visitante: {visitantes.Name} NÃO FOI CADASTRADO");
            return BadRequest("Nâo foi possível cadastrar o novo visitante");
        }
        public async Task<IActionResult> BuscarPorId(int? id)
        {
            var visitante = await _context.Visitantes.FindAsync(id);
            return View(visitante);
        }
        public async Task<IActionResult> Detalhes(int? id)
        {
            var visitante = await _context.Visitantes.FindAsync(id);
            var visianteexpirador = visitante.Dataentrada.AddDays(1);
            if (visianteexpirador > visitante.Dataentrada)
            {
                 ViewBag.Mensagem = $"Ainda não foi dado saída para o visitante {visitante.Name} que entrou dia {visitante.Dataentrada}";
                return View(visitante);
            }
            return View(visitante);

        }
        public async Task<IActionResult> Editar(int? id)
        {
            var visitante = await _context.Visitantes.FindAsync(id);
            
            return PartialView("Editar", visitante);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editar(int? id, Visitantes visitantes)
        {
            if (id == null) return BadRequest();
            if(ModelState.IsValid)
            {
                await _loggerService.MessagemLog($"Visitante Atualizado: {visitantes.Name}");
                _context.Visitantes.Update(visitantes);
                await _context.SaveChangesAsync();
                return Ok();
            }
            await _loggerService.MessagemLog($"Visitante não foi Atualizado: {visitantes.Name}");
            return BadRequest("Não foi possível Editar o cadastro");
        }
        [HttpPost]
        public async Task<IActionResult> DarSaida(int? id, [Bind("Id,DataSaida")] Visitantes visitantes)
        {
            var visitante = await _context.Visitantes.FindAsync(id);
            if (visitante == null) return BadRequest();
            visitante.DataSaida = visitantes.DataSaida;
            await _context.SaveChangesAsync();
            return Ok();
        }
        public async Task<IActionResult> DarSaidaView(int? id)
        {
            var saindoVisita = await _context.Visitantes.FindAsync(id);
            return PartialView("DarSaida", saindoVisita);
        }
        public async Task<IActionResult> Deletar(int? id)
        {
            var visitante = await _context.Visitantes.FindAsync(id);
            if(visitante == null) return BadRequest();
            return PartialView("Deletar", visitante);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [PaginaParaUsuarioAdmin]
        public async Task<IActionResult> DeletarVisitante(int? id, Usuarios usuarios)
        {
            if (id == null) return BadRequest();

            var visitante = await _context.Visitantes.FindAsync(id);
            if (visitante == null) return NotFound();
            var UsuarioLogado = _sessionUsuary.BuscarSessao();
            if (UsuarioLogado.Admin == true)
            {
                await _loggerService.MessagemLog($"Visitante: {visitante.Name} deletado com sucesso");
                _context.Visitantes.Remove(visitante);
                await _context.SaveChangesAsync();

                return Ok();
            }
            await _loggerService.MessagemLog($"Visitante: {visitante.Name} não pode ser deletado");
            return BadRequest("Opção disponível apenas para Administradores");
        }
    }
}

Prédio Comercial/Views/Visitantes/DarSaida.cshtml
@model Prédio_Comercial.Models.Visitantes;
<h2>Deseja Dar Saída em Visitante?</h2>
<form id="formEditarVisitante">
    <input type="hidden" asp-for="Id" />
    <div class="col-6">
        <label asp-for="DataSaida">Data da Saída</label>
        <input asp-for="DataSaida" type="datetime-local" class="form-control" />
        <span asp-validation-for="DataSaida" class="text-danger"></span>
    </div>
    <button class="btn btn-primary" type="submit">Saída</button>
    <button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancelar</button>

</form>

Prédio Comercial/Views/Visitantes/Deletar.cshtml
@model Prédio_Comercial.Models.Visitantes;

<form asp-controller="Visitantes" asp-action="DeletarVisitante" asp-route-id="@Model.Id" id="formDeletarVisitante">
    <input asp-for="Id" type="hidden" />
    <div class="col-4">

        <label asp-for="Name">Nome:</label>
        <input asp-for="Name" type="text" readonly class="form-control" />

    </div>
    <div class="col-4">
        <label asp-for="Documento">RG/CPF:</label>
        <input asp-for="Documento" readonly type="text" placeholder="000.000.000-00" class="form-control " />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="col-4">
        <label asp-for="Empresa">Empresa</label>
        <input asp-for="Empresa" type="text" readonly class="form-control" />
        <span asp-validation-for="Empresa" class="text-danger"></span>

    </div>

    <div class="col-4">
        <label asp-for="Dataentrada">Data da Entrada</label>
        <input asp-for="Dataentrada" readonly type="datetime-local" class="form-control" />
        <span asp-validation-for="Dataentrada" class="text-danger"></span>

    </div>
    <div class="col-4">
        <label asp-for="DataSaida">Data da Saída</label>
        <input asp-for="DataSaida" readonly type="datetime-local" class="form-control" />
        <span asp-validation-for="DataSaida" class="text-danger"></span>

    </div>
    <div class="col-4">
        <label asp-for="MotivoVisita">Motivo da Visita</label>
        <input asp-for="MotivoVisita" readonly type="text" class="form-control" />
        <span asp-validation-for="MotivoVisita" class="text-danger"></span>

    </div>
    <div class="col-4">
        <label asp-for="VisitandoQuem">Quem visitou</label>
        <input asp-for="VisitandoQuem" readonly type="text" class="form-control" />
        <span asp-validation-for="VisitandoQuem" class="text-danger"></span>

    </div>
    <button class="btn btn-primary" type="submit">Deletar</button>
</form>
<a asp-controller="Visitantes" asp-action="ListaVisitantes" class="btn btn-light">Voltar</a>

Prédio Comercial/Views/Visitantes/Detalhes.cshtml
@model Prédio_Comercial.Models.Visitantes;

<div class="container">
    <div class="row">
        @if (ViewBag.Mensagem != null)
        {
            <div class="container">
                <div class="row">
                    <div class="MensagenWarning alert alert-warning" role="alert">
                        <button style="display=block;" class="_BotaoMensagemFechar">X</button>
                        @ViewBag.Mensagem
                    </div>
                </div>
            </div>
        }

        <div class="col-12">
            <form asp-controller="Visitantes" asp-action="Detalhes">
                <input type="hidden" asp-for="Id" />
                <div class="col-md-6">

                    <label asp-for="Name">Nome:</label>
                    <input asp-for="Name" type="text" readonly class="form-control" />

                </div>
                <div class="col-md-6">
                    <label asp-for="Documento">RG/CPF:</label>
                    <input asp-for="Documento" type="text" readonly placeholder="000.000.000-00" class="form-control " />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="col-md-6">
                    <label asp-for="Empresa">Empresa</label>
                    <input asp-for="Empresa" type="text" readonly class="form-control" />
                    <span asp-validation-for="Empresa" class="text-danger"></span>

                </div>

                <div class="col-md-6">
                    <label asp-for="Dataentrada">Data da Entrada</label>
                    <input asp-for="Dataentrada" readonly type="datetime-local" class="form-control" />
                    <span asp-validation-for="Dataentrada" class="text-danger"></span>

                </div>
                <div class="col-md-6">
                    <label asp-for="DataSaida">Data da Saída</label>
                    <input asp-for="DataSaida" type="datetime-local" readonly class="form-control" />
                    <span asp-validation-for="DataSaida" class="text-danger"></span>

                </div>
                <div class="col-md-6">
                    <label asp-for="MotivoVisita">Motivo da Visita</label>
                    <input asp-for="MotivoVisita" readonly type="text" class="form-control" />
                    <span asp-validation-for="MotivoVisita" class="text-danger"></span>

                </div>
                <div class="col-md-6">
                    <label asp-for="VisitandoQuem">Quem visitou</label>
                    <input asp-for="VisitandoQuem" readonly type="text" class="form-control" />
                    <span asp-validation-for="VisitandoQuem" class="text-danger"></span>

                </div>
            </form>
        </div>
    </div>
</div>

                   

Prédio Comercial/Views/Visitantes/Editar.cshtml
@model Prédio_Comercial.Models.Visitantes;
@{
    ViewData["Title"] = "Editar Visitantes";
}

<h2>Editar Visitante</h2>

                <div class="container">
                    <div class="row">
                        <form class="form-control" asp-controller="Visitantes" asp-action="Editar" id="formEditarVisitante">
                            <input type="hidden" asp-for="Id" />
                             <div class="col-4">

                                <label asp-for="Name">Nome:</label>
                                <input asp-for="Name" type="text" class="form-control" />

                            </div>
                            <div class="col-4">
                                <label asp-for="Documento">RG/CPF:</label>
                                <input asp-for="Documento" type="text" placeholder="000.000.000-00" class="form-control " />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="col-4">
                                <label asp-for="Empresa">Empresa</label>
                                <input asp-for="Empresa" type="text" class="form-control" />
                                <span asp-validation-for="Empresa" class="text-danger"></span>

                            </div>

                            <div class="col-4">
                                <label asp-for="Dataentrada">Data da Entrada</label>
                                <input asp-for="Dataentrada" type="datetime-local" class="form-control" />
                                <span asp-validation-for="Dataentrada" class="text-danger"></span>
 
                            </div> 
                            <div class="col-4">
                                <label asp-for="DataSaida">Data da Saída</label>
                                <input asp-for="DataSaida" type="datetime-local" class="form-control" />
                                <span asp-validation-for="DataSaida" class="text-danger"></span>

                            </div>
                             <div class="col-4">
                                <label asp-for="MotivoVisita">Motivo da Visita</label>
                                <input asp-for="MotivoVisita" type="text" class="form-control" />
                                <span asp-validation-for="MotivoVisita" class="text-danger"></span>

                            </div>
                            <div class="col-4">
                                <label asp-for="VisitandoQuem">Quem visitou</label>
                                <input asp-for="VisitandoQuem" type="text" class="form-control" />
                                <span asp-validation-for="VisitandoQuem" class="text-danger"></span>

                            </div>
                             <button class="btn btn-primary" type="submit">Salvar</button>
                        </form>
                    </div>
                    <a asp-controller="Visitantes" asp-action="ListaVisitantes" class="btn btn-light">Voltar</a>
                </div>
     </div>
      

Prédio Comercial/Views/Visitantes/Index.cshtml
@model Prédio_Comercial.Models.Visitantes;
<style>
    .content {
        margin-left: 0px;
        padding: 20px;
    }
    .formulario{
        position: relative;
        display: flex;
        flex-direction: column;
    }
</style>

<div class="content container">
    <div class="row">
        <div class="col-12">
            <h2>Lista de Visitantes</h2>
           
            <div class="center">
                <form asp-controller="Visitantes" asp-action="NovoVisitante" class="align-items-center formulario">
                    <div class="col-md-6 col-12">

                        <label asp-for="Name">Nome:</label>
                        <input asp-for="Name" type="text" class="form-control" />

                    </div>
                    <div class="col-md-6 col-12">
                        <label asp-for="Documento">RG/CPF:</label>
                        <input asp-for="Documento" type="text" placeholder="000.000.000-00" class="form-control " />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="col-md-6 col-12">
                        <label asp-for="Empresa">Empresa</label>
                        <input asp-for="Empresa" type="text" class="form-control" />
                        <span asp-validation-for="Empresa" class="text-danger"></span>

                    </div>

                    <div class="col-md-6 col-12">
                        <label asp-for="Dataentrada">Data da Entrada</label>
                        <input asp-for="Dataentrada" type="date" class="form-control" />
                        <span asp-validation-for="Dataentrada" class="text-danger"></span>

                    </div>
                    <div class="col-md-6 col-12">
                        <label asp-for="DataSaida">Data da Saída</label>
                        <input asp-for="DataSaida" type="datetime-local" class="form-control" />
                        <span asp-validation-for="DataSaida" class="text-danger"></span>

                    </div>
                    <div class="col-md-6 col-12">
                        <label asp-for="MotivoVisita">Motivo da Visita</label>
                        <input asp-for="MotivoVisita" type="text" class="form-control" />
                        <span asp-validation-for="MotivoVisita" class="text-danger"></span>

                    </div>
                    <div class="col-md-6 col-12">
                        <label asp-for="VisitandoQuem">Quem visitou</label>
                        <input asp-for="VisitandoQuem" type="text" class="form-control" />
                        <span asp-validation-for="VisitandoQuem" class="text-danger"></span>

                    </div>
                    <div class="row">
                        <button class="btn btn-primary" type="submit">Cadastrar</button>

                    </div>
                </form>
            </div>
            <div class="row">
                <div class="col-4">
                    <a asp-controller="Visitantes" asp-action="ListaVisitantes" class="btn btn-light">Ver lista de Visitantes</a>

                </div>

            </div>
        </div>

    </div>
    </div>
    
    

Prédio Comercial/Views/Visitantes/ListaVisitantes.cshtml
@model IEnumerable<Prédio_Comercial.Models.Visitantes>;


    <style>

        </style>
@if (ViewBag.Mensagem != null)
{
    <div class="container">
        <div class="row">
            <div class="MensagenWarning alert alert-warning" role="alert">
                <button style="display=block;" class="_BotaoMensagemFechar">X</button>
                @ViewBag.Mensagem
            </div>
        </div>
    </div>
}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 col-12">
                <div class="table-responsive tabletable-responsive-lg">
                <h2 class="card-subtitle">Lista De Visitantes</h2>
                <a asp-controller="Visitantes" asp-action="ListaVisitantesAtivo" class="btn btn-info">Visitantes no Prédio</a>
                <table class="table table-dark">
                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model=>model.Name)</th>
                            <th>@Html.DisplayNameFor(model=>model.Empresa)</th>
                            <th>@Html.DisplayNameFor(model=>model.Dataentrada)</th>
                            <th>@Html.DisplayNameFor(model=>model.DataSaida)</th>
                            <th>@Html.DisplayNameFor(model=>model.VisitandoQuem)</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var x in Model)
                        {
                            <tr>
                                <td id="Nome">@Html.DisplayFor(modelitem=> x.Name)</td>


                                <td>@Html.DisplayFor(modelitem=> x.Empresa)</td>


                                <td>@Html.DisplayFor(modelitem=> x.Dataentrada)</td>


                                <td>@Html.DisplayFor(modelitem=> x.DataSaida)</td>


                                <td>@Html.DisplayFor(modelitem=> x.VisitandoQuem)</td>
                                <td>
                                    <a data-id="@x.Id" class="eventToolEditar btnCustonEdit btn-editar">
                                        
                                    </a>
                                    <p class="tooltipCustomEdit">Editar</p>
                                    <a data-id="@x.Id" class="eventTool btnCustomDelet btn-deletar">
                                        x
                                    </a>
                                    <p class="tooltipCustom">Deletar</p>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <a asp-controller="Visitantes" asp-action="Index" class="btn btn-light">Voltar</a>

            </div>
            </div>

        </div>

    </div>
    @section Box1{
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 col-lg-5">
                <form method="get" asp-action="ListaVisitantes" asp-controller="Visitantes" class="mb-3">
                        <div class="mb-3">
                            <label for="documento" class="form-label">Documento RG/CPF:</label>
                            <input type="text" name="documento" class="form-control" id="documento" required />
                        </div>
                        <button type="submit" class="btn btn-primary">Filtrar</button>
                    </form>
                </div>
                <div class="col-12 col-lg-6">
                <form method="get" asp-action="ListaVisitantes" asp-controller="Visitantes" class="mb-3">
                        <div class="mb-3">
                        <label for="Dataentrada" class="form-label">Data da Entrada</label>
                        <input for="Dataentrada" name="dateTime" type="datetime-local" class="form-control" />
                        </div>
                    <button type="submit" class="btn btn-primary">Filtrar</button>
                    </form>
                    </div>
                <div class="col-4 col-12">
                    <div class="table-responsive">
                            <table class="table table-dark">
                                <thead>
                                    <tr>
                                        <th>@Html.DisplayNameFor(models => models.Name)</th>
                                    </tr>
                                </thead>
                                <tbody>
                            @foreach(var y in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(models => y.Name)</td>
                                </tr>
                            }
                        </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }


<div class="col-md-3">

</div>
<!--Aqui é o MODAL que vai abrir o formulário para Edição-->

<div class="modal fade" id="modalEdicao" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Deseja Editar Visitante?</h1>
            <div class="modal-body" id="conteudoModalEdicao">

            </div>
        </div>
    </div>
</div> 
<!-- Aqui é onde abre o modal para confirmação de Deletar-->

<div class="modal fade" id="modalDelete" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Deseja Deletar Visitante?</h1>
            <div class="modal-body" id="conteudoModalDelete">

            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

<script>

    $(document).ready(function () {
        $('.btn-editar').click(function () {
            const id = $(this).data('id');

            $.ajax({
                type: "GET",
                url: "/Visitantes/Editar/" + id,
                success: function (html) {
                    $('#conteudoModalEdicao').html(html);
                    $('#modalEdicao').modal('show');
                },
                error: function () {
                    alert("Erro ao carregar formulário.");
                }
            });
        });

        $(document).on('submit', '#formEditarVisitante', function (e) {
            e.preventDefault();
            $.ajax({
                type: "POST",
                url: "/Visitantes/Editar/",
                data: $("#formEditarVisitante").serialize(),
                success: function (response) {
                    $('#modalEdicao').modal('hide');
                    location.reload();
                },
                error: function (xhr) {
                    alert("Erro ao salvar dados:" + xhr.responseText);
                }
            });
        });

    // Aqui vai o outro script para abrir o formulário para confirmar o Delete //

    
        $('.btn-deletar').click(function () {
            const id = $(this).data('id');

            $.ajax({
                type:"GET",
                url:"/Visitantes/Deletar/"+id,
                success: function (html) {
                    $('#conteudoModalDelete').html(html);
                    $('#modalDelete').modal('show');
                },
                error: function() {
                    alert("Erro ao carregar Visitante");
                }
            });
        });

        $(document).on('submit', '#formDeletarVisitante', function (e) {
            e.preventDefault();
            $.ajax({
                type:"POST",
                url: "/Visitantes/DeletarVisitante/",
                data: $("#formDeletarVisitante").serialize(),
                success: function (response) {
                    $('#modalDelete').modal('hide');
                    location.reload();
                },
                error: function(xhr) {
                    alert("Erro ao deletar o Visitante :" + xhr.responseText);
                }
            });
        });
    });
</script>

 

Prédio Comercial/Views/Visitantes/_EditarVisitante.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}