Prédio Comercial/Models/DTO/DashBoardDTO.cs
namespace Prédio_Comercial.Models.DTO
{
    public class DashBoardDTO
    {
        public List<string>? UsuariosLogin { get; set; }
        public int? TotalUsuarios { get; set; }
        public List<string>? ProprietariosName { get; set;}
        public int? TotalProprietarios { get; set; }
        public List<string>? VisitantesName { get; set; }
        public int? TotalVisitantes { get; set; }
        public int? TotalAcessos { get; set; }
        public int? TotalOcorrencias { get; set; }
        public DateTime DataInclusao { get; set; } = DateTime.Now;


    }
}

Prédio Comercial/Controllers/DashBoardDTOController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Prédio_Comercial.ActionFilter;
using Prédio_Comercial.Interface;
using Prédio_Comercial.Service;

namespace Prédio_Comercial.Controllers
{
    [PaginaParaUsuarioAdmin]
    public class DashBoardDTOController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IDashBoardDTO _dashBoardDTO;
        public DashBoardDTOController(ApplicationDbContext applicationDbContext, IDashBoardDTO dashBoardDTO)
        {
            _context = applicationDbContext;
            _dashBoardDTO = dashBoardDTO;
        }
        public async Task<IActionResult> Index(DateTime date)
        {
            if(date.Day > 1)
            {
                var filter = await _dashBoardDTO.GetUserDate(date);
                return View(filter);
            }
            return View( await _dashBoardDTO.GetDashBoardDTO());
        }
    }
}

Prédio Comercial/Views/DashBoardDTO/Index.cshtml
@model Prédio_Comercial.Models.DTO.DashBoardDTO;

<h2>DashBoard</h2>
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="table-responsive">
                <table class="table table-dark">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model=>model.VisitantesName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model=>model.ProprietariosName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model=>model.UsuariosLogin)
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                @foreach (var a in Model.VisitantesName)
                                {
                                    <li>@a</li>

                                }
                            </td>
                            <td>
                            @foreach(var a in Model.ProprietariosName)
                            {
                                    <li>@a</li>
                            }
                            </td>
                            <td>
                            @foreach(var a in Model.UsuariosLogin)
                            {
                                    <li>@a</li>
                            }
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col col-sm-6 col-lg-4">
            <div class="card">
                <div class="card-body">
                    <h7 class="card-title">Total de Acessos</h7>
                    <h4 class="card-text">@Model.TotalAcessos</h4>
                    <a href="#" class="btn btn-primary">Detalhes</a>
                </div>
            </div>
        </div>
        <div class="col col-sm-6 col-lg-4">
            <div class="card">
                <div class="card-body">
                    <h7 class="card-title">Total de Proprietários</h7>
                    <h4 class="card-text">@Model.TotalProprietarios</h4>
                    <a href="#" class="btn btn-primary">Detalhes</a>
                </div>
            </div>
        </div>
        <div class="col col-sm-6 col-lg-4">
            <div class="card">
                <div class="card-body">
                    <h7 class="card-title">Total de Visitantes</h7>
                    <h4 class="card-text">@Model.TotalVisitantes</h4>
                    <a href="#" class="btn btn-primary">Detalhes</a>
                </div>
            </div>
        </div>
        <div class="col col-sm-6 col-lg-4">
            <div class="card">
                <div class="card-body">
                    <h7 class="card-title">Total de Usuarios</h7>
                    <h4 class="card-text">@Model.TotalUsuarios</h4>
                    <a href="#" class="btn btn-primary">Detalhes</a>
                </div>
            </div>
        </div>
    </div>
</div>
@section box1{
    <h5>Filtrar Total de Visitantes</h5>
    <form method="get" asp-action="Index" asp-controller="DashBoardDTO">
        <label for="date" class="form-label"></label>
        <input type="datetime-local" name="date" class="form-control" />
        <button class="btnCustonEdit" type="submit"></button>
    </form>
}
@section box2{
    <h5>Filtrar Total de Usuarios</h5>
    <form method="get" asp-action="Index" asp-controller="DashBoardDTO">
        <label for="date" class="form-label"></label>
        <input type="datetime-local" name="date" class="form-control" />
        <button class="btnCustonEdit" type="submit"></button>
    </form>
}